// Auto-generated
let project = new Project('arrow2');

project.addSources('Sources');
project.addLibrary("D:/PF/Armory/Armory_04_win64_b27/Armory/armsdk/armory");
project.addLibrary("D:/PF/Armory/Armory_04_win64_b27/Armory/armsdk/iron");
project.addLibrary("mynodes");
project.addLibrary("D:/PF/Armory/Armory_04_win64_b27/Armory/armsdk/lib/haxebullet");
project.addAssets("D:/PF/Armory/Armory_04_win64_b27/Armory/armsdk/lib/haxebullet/js/ammo/ammo.js", { notinlist: true });
project.addParameter('armory.trait.internal.CanvasScript');
project.addParameter("--macro keep('armory.trait.internal.CanvasScript')");
project.addParameter('arm.node.FireArrow');
project.addParameter("--macro keep('arm.node.FireArrow')");
project.addParameter('arm.node.InitProperty');
project.addParameter("--macro keep('arm.node.InitProperty')");
project.addParameter('arm.node.GameUINode');
project.addParameter("--macro keep('arm.node.GameUINode')");
project.addParameter('arm.node.ArrowHit');
project.addParameter("--macro keep('arm.node.ArrowHit')");
project.addParameter('arm.node.PlayerControll');
project.addParameter("--macro keep('arm.node.PlayerControll')");
project.addParameter('armory.trait.physics.bullet.PhysicsWorld');
project.addParameter("--macro keep('armory.trait.physics.bullet.PhysicsWorld')");
project.addParameter('arm.node.MoveTarget');
project.addParameter("--macro keep('arm.node.MoveTarget')");
project.addParameter('armory.trait.physics.bullet.RigidBody');
project.addParameter("--macro keep('armory.trait.physics.bullet.RigidBody')");
project.addShaders('D:/Arts/Armory/arrow2/build_arrow2/compiled/Shaders/blur_edge_pass.frag.glsl');
project.addShaders('D:/Arts/Armory/arrow2/build_arrow2/compiled/Shaders/compositor_pass.frag.glsl');
project.addShaders('D:/Arts/Armory/arrow2/build_arrow2/compiled/Shaders/compositor_pass.vert.glsl');
project.addShaders('D:/Arts/Armory/arrow2/build_arrow2/compiled/Shaders/deferred_indirect.frag.glsl');
project.addShaders('D:/Arts/Armory/arrow2/build_arrow2/compiled/Shaders/deferred_indirect.vert.glsl');
project.addShaders('D:/Arts/Armory/arrow2/build_arrow2/compiled/Shaders/deferred_light.frag.glsl');
project.addShaders('D:/Arts/Armory/arrow2/build_arrow2/compiled/Shaders/deferred_light_quad.frag.glsl');
project.addShaders('D:/Arts/Armory/arrow2/build_arrow2/compiled/Shaders/pass.vert.glsl');
project.addShaders('D:/Arts/Armory/arrow2/build_arrow2/compiled/Shaders/pass_lamp_volume.vert.glsl');
project.addShaders('D:/Arts/Armory/arrow2/build_arrow2/compiled/Shaders/pass_viewray.vert.glsl');
project.addShaders('D:/Arts/Armory/arrow2/build_arrow2/compiled/Shaders/ssao_pass.frag.glsl');
project.addShaders('D:/Arts/Armory/arrow2/build_arrow2/compiled/Shaders/translucent_resolve.frag.glsl');
project.addShaders('D:/Arts/Armory/arrow2/build_arrow2/compiled/Shaders/world_pass.frag.glsl');
project.addShaders('D:/Arts/Armory/arrow2/build_arrow2/compiled/Shaders/world_pass.vert.glsl');
project.addShaders('build_arrow2/compiled/Shaders/Metal_mesh.frag.glsl');
project.addShaders('build_arrow2/compiled/Shaders/Metal_mesh.vert.glsl');
project.addShaders('build_arrow2/compiled/Shaders/Metal_shadowmap.frag.glsl');
project.addShaders('build_arrow2/compiled/Shaders/Metal_shadowmap.vert.glsl');
project.addShaders('build_arrow2/compiled/Shaders/Transparent_translucent.frag.glsl');
project.addShaders('build_arrow2/compiled/Shaders/Transparent_translucent.vert.glsl');
project.addShaders('build_arrow2/compiled/Shaders/armdefault_mesh.frag.glsl');
project.addShaders('build_arrow2/compiled/Shaders/ground_mesh.frag.glsl');
project.addShaders('build_arrow2/compiled/Shaders/ground_mesh.vert.glsl');
project.addShaders('build_arrow2/compiled/Shaders/ground_shadowmap.vert.glsl');
project.addShaders('build_arrow2/compiled/Shaders/red_mesh.frag.glsl');
project.addShaders('build_arrow2/compiled/Shaders/while_mesh.frag.glsl');
project.addShaders('build_arrow2/compiled/Shaders/wood_mesh.frag.glsl');
project.addAssets("build_arrow2/compiled/Shaders/Metal_data.arm", { notinlist: true });
project.addAssets("build_arrow2/compiled/Shaders/Transparent_data.arm", { notinlist: true });
project.addAssets("build_arrow2/compiled/Shaders/armdefault_data.arm", { notinlist: true });
project.addAssets("build_arrow2/compiled/Shaders/ground_data.arm", { notinlist: true });
project.addAssets("build_arrow2/compiled/Shaders/red_data.arm", { notinlist: true });
project.addAssets("build_arrow2/compiled/Shaders/shader_datas.arm", { notinlist: true });
project.addAssets("build_arrow2/compiled/Shaders/while_data.arm", { notinlist: true });
project.addAssets("build_arrow2/compiled/Shaders/wood_data.arm", { notinlist: true });
project.addAssets("../../pictures/circle.png", { notinlist: true });
project.addAssets("../../pictures/power_slider.png", { notinlist: true });
project.addAssets("Bundled/canvas/GameUI.files", { notinlist: true });
project.addAssets("Bundled/canvas/GameUI.json", { notinlist: true });
project.addAssets("D:/PF/Armory/Armory_04_win64_b27/Armory/armsdk/armory/Assets/brdf.png", { notinlist: true });
project.addAssets("D:/PF/Armory/Armory_04_win64_b27/Armory/armsdk/armory/Assets/noise8.png", { notinlist: true });
project.addAssets("D:/Arts/Armory/arrow2/build_arrow2/compiled/Assets/Scene.arm", { notinlist: true });
project.addAssets("D:/Arts/Armory/arrow2/build_arrow2/compiled/Assets/meshes/action_ArmatureBow_armorypose.arm", { notinlist: true });
project.addAssets("D:/Arts/Armory/arrow2/build_arrow2/compiled/Assets/meshes/mesh_ArrowHitMesh.arm", { notinlist: true });
project.addAssets("D:/Arts/Armory/arrow2/build_arrow2/compiled/Assets/meshes/mesh_Circle.002.arm", { notinlist: true });
project.addAssets("D:/Arts/Armory/arrow2/build_arrow2/compiled/Assets/meshes/mesh_Circle.arm", { notinlist: true });
project.addAssets("D:/Arts/Armory/arrow2/build_arrow2/compiled/Assets/meshes/mesh_Cube.001.arm", { notinlist: true });
project.addAssets("D:/Arts/Armory/arrow2/build_arrow2/compiled/Assets/meshes/mesh_MeshArrow.arm", { notinlist: true });
project.addAssets("D:/Arts/Armory/arrow2/build_arrow2/compiled/Assets/meshes/mesh_MeshBow.arm", { notinlist: true });
project.addAssets("D:/Arts/Armory/arrow2/build_arrow2/compiled/Assets/meshes/mesh_Plane.arm", { notinlist: true });
project.addAssets("D:/Arts/Armory/arrow2/build_arrow2/compiled/Assets/meshes/mesh_Sphere.arm", { notinlist: true });
project.addAssets("build_arrow2/compiled/Assets/envmaps/World_irradiance.arm", { notinlist: true });
project.addLibrary("D:/PF/Armory/Armory_04_win64_b27/Armory/armsdk/lib/zui");
project.addAssets("D:/PF/Armory/Armory_04_win64_b27/Armory/armsdk/armory/Assets/droid_sans.ttf", { notinlist: false });
project.addDefine('arm_deferred');
project.addDefine('arm_csm');
project.addDefine('rp_hdr');
project.addDefine('rp_renderer=Deferred');
project.addDefine('rp_shadowmap');
project.addDefine('rp_shadowmap_size=1024');
project.addDefine('rp_background=World');
project.addDefine('rp_render_to_texture');
project.addDefine('rp_compositornodes');
project.addDefine('rp_antialiasing=FXAA');
project.addDefine('rp_supersampling=1');
project.addDefine('rp_translucency');
project.addDefine('rp_gi=Off');
project.addDefine('rp_ssgi=SSAO');
project.addDefine('arm_physics');
project.addDefine('arm_bullet');
project.addDefine('arm_shaderload');
project.addDefine('arm_soundcompress');
project.addDefine('arm_ui');
project.addDefine('arm_fast');


resolve(project);
